# Generated by Django 4.1.7 on 2023-03-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_sph_lms", "0003_auto_20230308_1551"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
